### ISSUE TITLE
How can I make template & get template id on msg91

### ISSUE THREAD

**Issue by harshal255** [syncloudsoftech/msg91-node#1]
How can I make template & get template id on msg91
[](https://msg91.com/in)

const sent = await msg91.send(phoneNumber, "MSG91_TEMPLATE_ID");

I haven't idea about template id while I create template then need to DLT test...
how can i do that?

**Comment by vaibhavpandeyvpz** [comment]
Please refer to MSG91 docs https://msg91.com/help/where-to-find-the-sendotp-api-how-to-get-template-id
